spring:
server:
  port: 8761
eureka:
  instance:
    hostname: ps-gateway
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/